### ISSUE TITLE
Use default branch, not 'main' as fallback

### ISSUE THREAD

**Issue by pwtyler** [jazzsequence/action-validate-plugin-version#11]
```
  branch:
    description: The branch to use as the base for PRs and commit the changes back to.
    required: false
    default: 'main'
```
https://github.com/jazzsequence/action-validate-plugin-version/blob/main/action.yml#L24-L27

Input should not default to "main", but instead if not provided, should use the default branch (usually but not always main)
